os:
  - linux
services:
  - docker
install:
  - docker build -t simlife/simlife-registry:travis .
  - docker images
  - docker run --name simlife-registry -p 8761:8761 -d -t simlife/simlife-registry:travis
script:
  - sleep 45
  - docker ps
  - docker logs simlife-registry
  - curl -v http://localhost:8761
